config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#index'

  get 'static_pages/index'
  get 'sign_up', to: 'static_pages#sign_up'

  devise_for :posters
  devise_for :contractors
  
  #devise_scope :contractor do
  #  get 'sign_in', to: 'devise/sessions#new'
  #end

  #devise_scope :poster do
  #  get 'sign_in', to: 'devise/sessions#new'
  #end

  resources :posters
  resources :contractors
  resources :jobs

  #get 'contractor/:id' => 'contractors#show', as: :contractor
  #get 'poster/:id' => 'posters#show', as: :poster
end

app/models/contractor.rb
class Contractor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :poster
end

app/models/poster.rb
class Poster < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit!}
  end

  # Overwriting the sign_out redirect path method
  def after_sign_in_path_for(resource)
    if contractor_signed_in?
      contractor_url(resource)
    else poster_signed_in?
      poster_url(resource)
    end
  end

end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  before_action :set_contractor, only: [:show, :edit, :update, :destroy]

  def index
    @contractors = Contractor.all
  end

  def show
    @contractor = Contractor.find(params[:id])
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contractor
      @contractor = Contractor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contractor_params
      params[:contractor]
    end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_poster!, except: [:index, :show]
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show

  end

  # GET /jobs/new
  def new
    @poster = current_poster
    @job = @poster.jobs.new
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = current_poster.jobs.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to current_poster, notice: 'Job posting was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    @job = current_poster.jobs.find(params[:id])

    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to current_poster, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:jobname, :description, :poster_id)
    end
end

app/controllers/posters_controller.rb
class PostersController < ApplicationController

  def index
    @posters= Poster.all
  end

  def show
    @poster= Poster.find(params[:id])
    @jobs = @poster.jobs.all 
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def index
  end

  def sign_up
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger"    # Red
      when "alert"
        "alert-warning"   # Yellow
      when "notice"
        "alert-info"      # Blue
      else
        flash_type.to_s
    end
  end
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/posters_helper.rb
module PostersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contractors/index.html.erb
contractor#index

app/views/contractors/show.html.erb
<div class="container devise-form">
  <div class="row">
    <div class="col-md-12">
      <h1>User Name: <%= @contractor.username %></h1>
    </div>
  </div>
</div>

app/views/jobs/_form.html.erb
<%= bootstrap_form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :jobname %>
    <%= f.number_field :budget %>
    <%= f.text_field :type_work %>
    <%= f.text_field :action_stage %>
    <%= f.text_field :status %>
    <%= f.text_area :description %>
  </div>
  
  <div class="actions">
    <%= f.primary "Save Job Listing" %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Edit Job Post</h1>

      <%= render 'form' %>

      <%= link_to 'Show', @job %> |
      <%= link_to 'Back', :back %>
    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Job Listings</h1>

      <table class="table">
        <thead>
          <tr>
            <th>Job Name:</th>
            <th>Description:</th>
            <th>Posted by:</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @jobs.each do |job| %>
            <tr>
              <td><%= job.jobname %></td>
              <td><%= job.description %></td>
              <td><%= job.poster.username%></td>
              <td><%= link_to 'Show', job %></td>
            <% if poster_signed_in? %>
              <td><%= link_to 'Edit', edit_job_path(job) %></td>
              <td><%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Job', new_job_path %>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>New job</h1>

      <%= render 'form' %>

      <%= link_to 'Back', :back %>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">

      <h4>
        <strong>Jobname:</strong>
        <%= @job.jobname %>
      </h4>

      <h4>
        <strong>Description:</strong>
        <%= @job.description %>
      </h4>

      <h4>
        <strong>Poster:</strong>
        <%= @job.poster.username %>
      </h4>
      <% if poster_signed_in? %>
        <%= link_to 'Edit', edit_job_path(@job) %> |
        <%= link_to 'Back', poster_path %>
      <% else %>  
        <%= link_to 'Back', jobs_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<hr>
<div id="footer">
  <div class="container">
    <p class="text-muted">&copy; BuilderSource 2014</p>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'BuilderSource', root_path, class: "navbar-brand"  %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div><!--/.navbar-collapse -->
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<% if poster_signed_in? %>
  <li><%= link_to 'Dashboard', current_poster %></li>
  <li><%= link_to 'Edit profile', edit_poster_registration_path %></li>
  <li><%= link_to "Logout", destroy_poster_session_path, method: :delete %></li>
<% elsif contractor_signed_in? %>
  <li><%= link_to 'Edit profile', edit_contractor_registration_path %></li>
  <li><%= link_to "Logout", destroy_contractor_session_path, method: :delete %></li>

<% else %>
  <li><%= link_to "Sign Up", sign_up_path %></li>
  <li><%= link_to "Job Poster Log In", new_poster_session_path %></li>
  <li><%= link_to "Contractor Log In", new_contractor_session_path %></li>
<% end %>

app/views/layouts/_shim.html.erb
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

  <title>BuilderSource</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render partial: "layouts/flash_messages", flash: flash %> 


    <%= yield %>

  <%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/posters/index.html.erb
<div class="container devise-form">
  <div class="row">
    <div class="col-md-12">
      <h1>Job Posters:</h1>

      <table class="table">
        <thead>
          <tr>
            <th>Job Name:</th>
            <th>Description:</th>
            <th>Posted by:</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @posters.each do |poster| %>
            <tr>
              <td><%= poster.username %></td>
              <td><%= link_to 'Show', poster %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/posters/show.html.erb
<div class="container devise-form">
  <div class="row">
    <div class="col-md-12">
      <h1>Job Poster: <%= @poster.username %></h1>
      <p><%= link_to "Create New Job Listing", new_job_path(@poster), class: "btn btn-primary btn-link" %></p>
      <table class="table">
        <thead>
          <tr>
            <th>Job Name:</th>
            <th>Description:</th>
            <th>Posted by:</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @jobs.each do |job| %>
            <tr>
              <td><%= job.jobname %></td>
              <td><%= job.description %></td>
              <td><%= job.poster.username%></td>
              <td><%= link_to 'Show', job %></td>
              <% if poster_signed_in? %>
              <td><%= link_to 'Edit', edit_job_path(job) %></td>
              <td><%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/static_pages/index.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container text-center">
    <h1>BuilderSource</h1>
    <p>This is is the base template for BuilderSource</p>
    <p><%= link_to "Sign Up Now!", sign_up_path, class: "btn btn-primary btn-lg" %></p>
  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
   </div>
    <div class="col-md-4">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
  </div>
</div>

app/views/static_pages/sign_up.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 well signup">
      <h2 class="text-center">Sign up for an account today!</h2>
      <div class="row text-center">
        <div class="col-md-3 signup-box">
          <h3>Are you a Job Poster?</h3>
          <p>Sign up for a free account now.</p>
          <div><%= link_to "Sign Up Now!", new_poster_registration_path, class: "btn btn-success btn-lg" %></div>
        </div>
        <div class="col-md-3 signup-box">
          <h3>Are you a Contractor?</h3>
          <p>Sign up for a free account now.</p>
          <div><%= link_to "Sign Up Now!", new_contractor_registration_path, class: "btn btn-success btn-lg" %></div>
        </div>
      </div>
    </div>
  </div>
</div>